import { readFile } from 'node:fs/promises'
import { expect, goToTab, openAppOnTuesday, openStoragePage, test } from './fixtures'
import type { Page } from '@playwright/test'

const today = '2026-09-22'
async function financeArea(page: Page, name: 'Visão geral' | 'Planejamento' | 'Patrimônio' | 'Ferramentas') {
  await page.getByRole('navigation', { name: 'Áreas do Financeiro' }).getByRole('button', { name, exact: true }).click()
}
async function tool(page: Page, name: string) {
  if (name === 'Recorrências e parcelas') await financeArea(page, 'Planejamento')
  else if (name === 'Patrimônio') await financeArea(page, 'Patrimônio')
  else {
    await financeArea(page, 'Ferramentas')
    await page.getByRole('group', { name: 'Ferramentas financeiras' }).getByRole('button', { name, exact: true }).click()
  }
}
async function addAccount(page: Page, name: string, balance: string, kind = 'bank') {
  await tool(page, 'Patrimônio')
  await page.getByRole('button', { name: 'Cadastrar conta ou dívida', exact: true }).click()
  const form = page.getByRole('form', { name: 'Conta patrimonial' })
  await form.getByLabel('Nome da conta', { exact: true }).fill(name)
  await form.getByLabel('Tipo de patrimônio', { exact: true }).selectOption(kind)
  await form.getByLabel('Saldo inicial (R$)', { exact: true }).fill(balance)
  await form.getByRole('button', { name: 'Salvar conta', exact: true }).click()
  await expect(form).not.toBeVisible()
}
async function recurrence(page: Page, name: string, type: string, amount: string, account = '', paymentMethod = '') {
  await tool(page, 'Recorrências e parcelas')
  await page.getByRole('button', { name: 'Criar recorrência', exact: true }).click()
  const form = page.getByRole('form', { name: 'Planejamento recorrente' })
  await form.getByLabel('Nome do planejamento', { exact: true }).fill(name)
  await form.getByLabel('Tipo da recorrência', { exact: true }).selectOption(type)
  await form.getByLabel('Valor recorrente (R$)', { exact: true }).fill(amount)
  if (type === 'saida' || type === 'pendencia') {
    expect(await form.getByLabel('Forma de pagamento', { exact: true }).locator('option:not([hidden])').allTextContents()).toEqual(['Cartão de crédito', 'Débito', 'Alimentação'])
    if (paymentMethod) await form.getByLabel('Forma de pagamento', { exact: true }).selectOption(paymentMethod)
  } else await expect(form.getByLabel('Forma de pagamento', { exact: true })).toHaveCount(0)
  if (account) await form.getByLabel('Conta prevista', { exact: true }).selectOption({ label: account })
  await form.getByRole('button', { name: 'Salvar planejamento', exact: true }).click()
  await expect(form).not.toBeVisible()
}
async function confirm(page: Page, name: string, double = false) {
  await page.getByRole('region', { name: 'Ocorrências do período' }).getByRole('button', { name: `Confirmar ${name} ${today}`, exact: true }).click()
  const form = page.getByRole('form', { name: 'Confirmar ocorrência' })
  if (double) await form.evaluate(element => { element.dispatchEvent(new Event('submit', { bubbles: true, cancelable: true })); element.dispatchEvent(new Event('submit', { bubbles: true, cancelable: true })) })
  else await form.getByRole('button', { name: /Confirmar recebimento\/pagamento|Confirmar valor em aberto/ }).click()
  await expect(form).not.toBeVisible()
}
async function backup(page: Page) {
  await goToTab(page, 'Ajustes')
  const download = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Exportar backup JSON', exact: true }).click()
  return JSON.parse((await readFile((await (await download).path())!)).toString('utf8'))
}

for (const theme of ['light', 'dark'] as const) test(`recorrências, parcelas, patrimônio, cenários e backup offline no tema ${theme}`, async ({ page, context }, testInfo) => {
  await openAppOnTuesday(page)
  await goToTab(page, 'Ajustes')
  await page.getByRole('button', { name: theme === 'light' ? 'Claro' : 'Escuro', exact: true }).click()
  await goToTab(page, 'Financeiro')
  await addAccount(page, 'Conta principal', '100000')
  await addAccount(page, 'Poupança', '0', 'savings')
  await addAccount(page, 'Dívida original', '30000', 'liability')
  await expect(page.getByRole('region', { name: 'Patrimônio financeiro' })).toContainText('700,00')
  await recurrence(page, 'Renda mensal', 'entrada', '10000', 'Conta principal')
  await financeArea(page, 'Visão geral')
  const summary = page.getByRole('region', { name: 'Resumo financeiro', exact: true })
  await expect(summary).toContainText('Sem dados')
  await financeArea(page, 'Planejamento')
  await confirm(page, 'Renda mensal', true)
  await financeArea(page, 'Visão geral')
  await expect(summary).toContainText('100,00')
  await recurrence(page, 'Conta fixa', 'saida', '5000', 'Conta principal')
  await confirm(page, 'Conta fixa')
  await page.getByRole('button', { name: 'Criar parcelamento', exact: true }).click()
  const installment = page.getByRole('form', { name: 'Novo parcelamento' })
  await installment.getByLabel('Nome do planejamento', { exact: true }).fill('Compra parcelada')
  await installment.getByLabel('Valor total da compra (R$)', { exact: true }).fill('10000')
  await installment.getByLabel('Quantidade de parcelas', { exact: true }).fill('3')
  await installment.getByLabel('Conta prevista', { exact: true }).selectOption({ label: 'Conta principal' })
  await installment.getByLabel('Dívida a reduzir após pagamento', { exact: true }).selectOption({ label: 'Dívida original' })
  await expect(installment).toContainText('primeira R$ 33,34, última R$ 33,33')
  await installment.getByRole('button', { name: 'Salvar planejamento', exact: true }).click()
  await confirm(page, 'Compra parcelada parcela 1')
  await expect(page.getByRole('region', { name: 'Parcelamentos cadastrados' })).toContainText('1 paga(s) · 2 restante(s) · saldo restante R$ 66,66')
  await financeArea(page, 'Visão geral')
  await expect(summary).toContainText('16,66')
  await tool(page, 'Patrimônio')
  const wealth = page.getByRole('region', { name: 'Patrimônio financeiro' })
  await expect(wealth).toContainText('1.016,66')
  await expect(wealth).toContainText('266,66')
  await expect(wealth).toContainText('750,00')
  await page.getByRole('button', { name: 'Transferir entre contas', exact: true }).click()
  const transfer = page.getByRole('form', { name: 'Transferência entre contas' })
  await transfer.getByLabel('Conta de origem', { exact: true }).selectOption({ label: 'Conta principal' })
  await transfer.getByLabel('Conta de destino', { exact: true }).selectOption({ label: 'Poupança' })
  await transfer.getByLabel('Valor da transferência (R$)', { exact: true }).fill('10000')
  await transfer.getByRole('button', { name: 'Salvar transferência', exact: true }).click()
  await expect(wealth).toContainText('916,66')
  await financeArea(page, 'Visão geral')
  await expect(summary).toContainText('16,66')
  await tool(page, 'Fechamento mensal')
  const closing = page.getByRole('region', { name: 'Fechamento mensal', exact: true })
  await expect(closing).toContainText('750,00')
  await expect(closing).toContainText('16,66')
  for (const width of [320, 390, 768, 1440]) {
    await page.setViewportSize({ width, height: 844 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    if (width === 390) await page.screenshot({ path: testInfo.outputPath(`fechamento-${theme}.png`), fullPage: true })
  }
  await tool(page, 'Simulador')
  const simulator = page.getByRole('region', { name: 'Simulador financeiro' })
  await simulator.getByLabel('Aumento de renda (R$)', { exact: true }).fill('10000')
  await simulator.getByLabel('Compra simulada (R$)', { exact: true }).fill('5000')
  await expect(simulator).toContainText('66,66')
  await financeArea(page, 'Visão geral')
  await expect(summary).toContainText('16,66')
  await tool(page, 'Exportações')
  for (const [label, extension, header] of [['CSV', 'csv', '\uFEFF'], ['Excel', 'xlsx', 'PK'], ['PDF', 'pdf', '%PDF-1.4']] as const) {
    const download = page.waitForEvent('download')
    await page.getByRole('button', { name: `Exportar ${label}`, exact: true }).click()
    const file = await download
    expect(file.suggestedFilename()).toBe(`rotina-financeiro-2026-09-01-2026-09-30.${extension}`)
    const bytes = await readFile((await file.path())!)
    expect(bytes.toString(extension === 'csv' ? 'utf8' : 'latin1').startsWith(header)).toBe(true)
    await file.saveAs(testInfo.outputPath(`financeiro.${extension}`))
  }
  const data = await backup(page)
  expect(data.recurringPlans).toHaveLength(2)
  expect(data.installmentPlans).toHaveLength(1)
  expect(data.assetAccounts).toHaveLength(3)
  expect(data.accountTransfers).toHaveLength(1)
  expect(data.financialRecords).toHaveLength(3)
  expect(data.financialRecords.filter((r: { description: string }) => r.description === 'Renda mensal')).toHaveLength(1)
  expect(data.installmentPlans[0]).not.toHaveProperty('remaining')
  page.once('dialog', d => d.accept())
  await page.locator('input[type="file"]').setInputFiles({ name: 'financeiro.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(data)) })
  await expect(page.getByRole('heading', { name: 'Um dia de cada vez.', exact: true })).toBeVisible()
  await page.evaluate(async () => navigator.serviceWorker.ready)
  await page.reload()
  await expect.poll(() => page.evaluate(() => !!navigator.serviceWorker.controller)).toBe(true)
  await context.setOffline(true)
  await page.reload()
  await goToTab(page, 'Financeiro')
  await expect(summary).toContainText('16,66')
  await financeArea(page, 'Planejamento')
  await expect(page.getByRole('region', { name: 'Parcelamentos cadastrados' })).toContainText('66,66')
  await tool(page, 'Patrimônio')
  await expect(wealth).toContainText('750,00')
  await goToTab(page, 'Progresso')
  await expect(page.getByRole('region', { name: 'Resumo financeiro', exact: true })).toContainText('16,66')
})

test('recorrências de crédito e pendência mantêm identidade após baixas e pausa', async ({ page }) => {
  await openAppOnTuesday(page)
  await goToTab(page, 'Financeiro')
  await recurrence(page, 'Crédito recorrente', 'credito', '10000')
  await recurrence(page, 'Pendência recorrente', 'pendencia', '3000')
  await confirm(page, 'Crédito recorrente')
  await confirm(page, 'Pendência recorrente')
  await financeArea(page, 'Visão geral')
  const history = page.getByRole('region', { name: 'Histórico financeiro' })
  await history.getByRole('button', { name: 'Receber', exact: true }).click()
  await history.getByRole('button', { name: 'Pagar', exact: true }).click()
  await expect(page.getByRole('region', { name: 'Resumo financeiro', exact: true })).toContainText('70,00')
  await financeArea(page, 'Planejamento')
  await page.getByRole('button', { name: 'Pausar Crédito recorrente', exact: true }).click()
  await expect(page.getByRole('region', { name: 'Recorrências cadastradas' })).toContainText('Pausada')
  const data = await backup(page)
  expect(data.financialRecords).toHaveLength(2)
  expect(data.financialRecords.every((r: { planningRef?: unknown }) => !!r.planningRef)).toBe(true)
  await goToTab(page, 'Financeiro')
  await financeArea(page, 'Planejamento')
  await page.getByRole('button', { name: 'Retomar Crédito recorrente', exact: true }).click()
  await expect(page.getByRole('region', { name: 'Ocorrências do período' }).getByRole('button', { name: /Confirmar Crédito/ })).toHaveCount(0)
})

test('recorrência de saída entra em A pagar e passa para Saídas quando paga', async ({ page }) => {
  await openAppOnTuesday(page)
  await goToTab(page, 'Financeiro')
  await recurrence(page, 'Aluguel', 'saida', '15000')
  await financeArea(page, 'Visão geral')
  const summary = page.getByRole('region', { name: 'Resumo financeiro', exact: true })
  const payable = summary.getByText('A pagar; reserva separada', { exact: true }).locator('..')
  const exits = summary.getByText('Saídas', { exact: true }).locator('..')
  const historyItem = page.getByRole('region', { name: 'Histórico financeiro' }).getByRole('article').filter({ hasText: 'Aluguel' })

  await expect(payable).toContainText('150,00')
  await expect(exits).toContainText('Sem dados')
  await expect(historyItem).toContainText('A pagar')
  await expect(historyItem).toContainText('Planejado')

  await financeArea(page, 'Planejamento')
  await confirm(page, 'Aluguel')
  await financeArea(page, 'Visão geral')

  await expect(payable).toContainText('0,00')
  await expect(exits).toContainText('150,00')
  await expect(historyItem).toContainText('Saída')
  await expect(historyItem).toContainText('Realizado')
})

for (const theme of ['light', 'dark'] as const) test(`visão anual de gastos recorrentes no tema ${theme}, responsiva, acessível e offline`, async ({ page, context }, testInfo) => {
  await openAppOnTuesday(page)
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await goToTab(page, 'Ajustes')
  await page.getByRole('button', { name: theme === 'light' ? 'Claro' : 'Escuro', exact: true }).click()
  await goToTab(page, 'Financeiro')
  await recurrence(page, 'Conta anual', 'saida', '5000', '', 'credito')

  const annual = page.getByRole('region', { name: 'Gastos recorrentes do ano' })
  await expect(annual).toContainText('Total anual planejado')
  await expect(annual).toContainText('R$ 200,00')
  await expect(annual.getByRole('button', { name: /^Janeiro de 2026/ })).toContainText('Sem compromissos')
  await expect(annual.locator('.recurring-year-month')).toHaveCount(12)

  const september = annual.getByRole('button', { name: /^Setembro de 2026/ })
  await september.focus()
  await expect(september).toBeFocused()
  await september.press('Enter')
  const details = annual.getByRole('region', { name: 'Ocorrências de Setembro de 2026' })
  await expect(details).toContainText('Conta anual')
  await expect(details).toContainText('Cartão de crédito')
  await expect(details).toContainText('Planejado')
  await details.getByRole('button', { name: 'Confirmar Conta anual 2026-09-22', exact: true }).click()
  await page.getByRole('form', { name: 'Confirmar ocorrência' }).getByRole('button', { name: 'Confirmar recebimento/pagamento', exact: true }).click()
  await expect(details).toContainText('Realizado')
  await expect(annual).toContainText('Total anual realizado')
  await expect(annual).toContainText('R$ 50,00')
  const storedPayment = await page.evaluate(async () => new Promise<string | undefined>((resolve, reject) => {
    const request = indexedDB.open('rotina-local')
    request.onerror = () => reject(request.error)
    request.onsuccess = () => {
      const db = request.result, tx = db.transaction('financialRecords', 'readonly'), rows = tx.objectStore('financialRecords').getAll()
      tx.oncomplete = () => { resolve(rows.result.find((row: { description: string }) => row.description === 'Conta anual')?.paymentMethod); db.close() }
      tx.onerror = () => reject(tx.error)
    }
  }))
  expect(storedPayment).toBe('credito')

  await annual.getByRole('button', { name: 'Ano anterior', exact: true }).click()
  await expect(annual.getByLabel('Ano civil', { exact: true })).toHaveValue('2025')
  await annual.getByRole('button', { name: 'Ano seguinte', exact: true }).click()
  await expect(annual.getByLabel('Ano civil', { exact: true })).toHaveValue('2026')

  for (const width of [320, 390, 768, 1440]) {
    await page.setViewportSize({ width, height: width === 768 ? 560 : 844 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    const targets = await annual.locator('button').evaluateAll(elements => elements.map(element => ({ width: element.getBoundingClientRect().width, height: element.getBoundingClientRect().height })))
    expect(targets.every(target => target.width >= 44 && target.height >= 44)).toBe(true)
    if (width === 390 || width === 1440) await page.screenshot({ path: testInfo.outputPath(`gastos-recorrentes-${theme}-${width}.png`), fullPage: true })
  }
  const contrasts = await annual.locator('.recurring-year-month, .recurring-year-totals article, .recurring-year-details').evaluateAll(elements => elements.map(element => {
    const color = getComputedStyle(element).color, background = getComputedStyle(element).backgroundColor
    const luminance = (text: string) => text.match(/[\d.]+/g)!.slice(0, 3).map(Number).map(channel => channel / 255).map(channel => channel <= 0.04045 ? channel / 12.92 : ((channel + 0.055) / 1.055) ** 2.4).reduce((sum, channel, index) => sum + channel * [0.2126, 0.7152, 0.0722][index], 0)
    const a = luminance(color), b = luminance(background)
    return (Math.max(a, b) + 0.05) / (Math.min(a, b) + 0.05)
  }))
  expect(contrasts.every(contrast => contrast >= 4.5)).toBe(true)

  await page.reload()
  await goToTab(page, 'Financeiro')
  await financeArea(page, 'Planejamento')
  await expect(page.getByRole('region', { name: 'Gastos recorrentes do ano' })).toContainText('R$ 50,00')
  await page.evaluate(async () => navigator.serviceWorker.ready)
  await expect.poll(() => page.evaluate(() => !!navigator.serviceWorker.controller)).toBe(true)
  await context.setOffline(true)
  await page.reload()
  await goToTab(page, 'Financeiro')
  await financeArea(page, 'Planejamento')
  await expect(page.getByRole('region', { name: 'Gastos recorrentes do ano' })).toContainText('Conta anual')
})

test('migração 4 para 7 preserva dados e backup antigo restaura novas coleções vazias', async ({ page }) => {
  await openStoragePage(page)
  await page.evaluate(async () => new Promise<void>((resolve, reject) => {
    const request = indexedDB.open('rotina-local', 4)
    request.onupgradeneeded = () => { for (const name of ['completions', 'dailySnapshots', 'checkIns', 'deliveryShifts', 'expenses', 'financialRecords', 'financialGoals', 'categoryBudgets', 'studyLogs', 'progress', 'settings']) request.result.createObjectStore(name, { keyPath: 'id' }) }
    request.onerror = () => reject(request.error)
    request.onsuccess = () => { const db = request.result, tx = db.transaction('financialRecords', 'readwrite'); tx.objectStore('financialRecords').put({ id: 'old', description: 'Renda legada', type: 'entrada', amount: 90, category: 'Outros', localDate: '2026-09-22', createdAt: '2026-09-22T13:00:00.000Z' }); tx.oncomplete = () => { db.close(); resolve() } }
  }))
  await openAppOnTuesday(page)
  await goToTab(page, 'Financeiro')
  await expect(page.getByRole('region', { name: 'Resumo financeiro', exact: true })).toContainText('90,00')
  const version = await page.evaluate(async () => new Promise<number>(resolve => { const request = indexedDB.open('rotina-local'); request.onsuccess = () => { resolve(request.result.version); request.result.close() } }))
  expect(version).toBe(7)
  const old = await backup(page)
  for (const key of ['recurringPlans', 'installmentPlans', 'assetAccounts', 'accountTransfers']) delete old[key]
  await goToTab(page, 'Financeiro')
  await addAccount(page, 'Temporária', '10000')
  await goToTab(page, 'Ajustes')
  page.once('dialog', d => d.accept())
  await page.locator('input[type="file"]').setInputFiles({ name: 'antigo.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(old)) })
  await expect(page.getByRole('heading', { name: 'Um dia de cada vez.', exact: true })).toBeVisible()
  const restored = await backup(page)
  for (const key of ['recurringPlans', 'installmentPlans', 'assetAccounts', 'accountTransfers']) expect(restored[key]).toEqual([])
  expect(restored.financialRecords).toHaveLength(1)
})
