import { expect, goToTab, openAppOnTuesday, test } from './fixtures'

for (const theme of ['light', 'dark'] as const) test(`menu em tela cheia, teclado e responsividade no tema ${theme}`, async ({ page }) => {
  await openAppOnTuesday(page)
  await goToTab(page, 'Ajustes')
  await page.getByRole('button', { name: theme === 'light' ? 'Claro' : 'Escuro', exact: true }).click()
  await goToTab(page, 'Financeiro')
  const trigger = page.getByRole('button', { name: 'Abrir menu principal', exact: true })
  for (const size of [{ width: 320, height: 568 }, { width: 390, height: 844 }, { width: 768, height: 1024 }, { width: 1440, height: 900 }, { width: 844, height: 390 }]) {
    await page.setViewportSize(size)
    await trigger.click()
    const menu = page.getByRole('dialog', { name: 'Menu principal' })
    await expect(menu).toBeVisible()
    expect(await menu.boundingBox()).toEqual({ x: 0, y: 0, ...size })
    await expect(menu.getByRole('button', { name: 'Financeiro', exact: true })).toBeFocused()
    const choices = menu.getByRole('navigation').getByRole('button')
    expect(await choices.allTextContents()).toEqual(['Hoje', 'Semana', 'Treinos', 'Registros', 'Financeiro', 'Progresso', 'Ajustes'])
    await expect(menu.locator('nav svg')).toHaveCount(0)
    expect(await page.evaluate(() => document.documentElement.style.overflow)).toBe('hidden')
    await menu.getByRole('button', { name: 'Fechar menu principal', exact: true }).click()
    await expect(menu).not.toBeVisible()
    await expect(trigger).toBeFocused()
    await expect(page.getByRole('heading', { name: 'Financeiro', exact: true })).toBeVisible()
  }
  await trigger.click()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog', { name: 'Menu principal' })).not.toBeVisible()
  await expect(trigger).toBeFocused()
  await trigger.click()
  await page.keyboard.press('Tab')
  await page.keyboard.press('Tab')
  await page.keyboard.press('Tab')
  const inside = await page.evaluate(() => document.querySelector('dialog[open]')?.contains(document.activeElement))
  expect(inside).toBe(true)
  await page.getByRole('dialog').getByRole('button', { name: 'Registros', exact: true }).click()
  await expect(page.getByRole('dialog', { name: 'Menu principal' })).not.toBeVisible()
  await expect(page.getByRole('heading', { name: 'Registros', exact: true })).toBeVisible()
  await expect(page.locator('#main-content')).toBeFocused()
  await expect(page.locator('.bottom-nav button')).toHaveCount(1)
  expect(await page.evaluate(() => document.documentElement.style.overflow)).not.toBe('hidden')
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await trigger.click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.screenshot({ path: test.info().outputPath(`menu-${theme}.png`) })
})
