import { expect, goToTab, openAppOnTuesday, test } from './fixtures'

test('oferece ações rápidas sem aumentar os destinos principais', async ({ page }) => {
  await openAppOnTuesday(page)
  await page.getByRole('button', { name: 'Abrir menu principal', exact: true }).click()

  const actions = page.getByRole('group', { name: 'Ações rápidas' })
  await expect(actions.getByRole('button')).toHaveText(['Turno', 'Estudo', 'Entrada', 'Saída'])
  await actions.getByRole('button', { name: 'Estudo', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Registros', exact: true })).toBeVisible()
  await expect(page.getByRole('group', { name: 'Tipo de registro' }).getByRole('button', { name: 'Estudos', exact: true })).toHaveAttribute('aria-pressed', 'true')

  await page.getByRole('button', { name: 'Abrir menu principal', exact: true }).click()
  await page.getByRole('group', { name: 'Ações rápidas' }).getByRole('button', { name: 'Saída', exact: true }).click()
  await expect(page.getByRole('form', { name: 'Registrar saída', exact: true })).toBeVisible()
})

for (const theme of ['light', 'dark'] as const) test(`menu em tela cheia, teclado e responsividade no tema ${theme}`, async ({ page }) => {
  await openAppOnTuesday(page)
  await goToTab(page, 'Ajustes')
  await page.getByRole('button', { name: theme === 'light' ? 'Claro' : 'Escuro', exact: true }).click()
  await goToTab(page, 'Financeiro')
  const trigger = page.getByRole('button', { name: 'Abrir menu principal', exact: true })
  for (const size of [{ width: 320, height: 568 }, { width: 390, height: 844 }, { width: 768, height: 1024 }, { width: 1440, height: 900 }, { width: 844, height: 390 }]) {
    await page.setViewportSize(size)
    const triggerBox = await trigger.boundingBox()
    expect(triggerBox).not.toBeNull()
    expect(triggerBox!.x).toBeLessThanOrEqual(24)
    expect(triggerBox!.width).toBeLessThanOrEqual(64)
    await expect(trigger).toHaveText('')
    await trigger.click()
    const menu = page.getByRole('dialog', { name: 'Menu principal' })
    await expect(menu).toBeVisible()
    expect(await menu.boundingBox()).toEqual({ x: 0, y: 0, ...size })
    await expect(menu.getByRole('button', { name: 'Financeiro', exact: true })).toBeFocused()
    await expect(menu.getByRole('heading', { name: 'Menu principal' })).toHaveCount(0)
    const choices = menu.getByRole('navigation').getByRole('button')
    expect(await choices.allTextContents()).toEqual(['Hoje', 'Semana', 'Treinos', 'Registros', 'Financeiro', 'Progresso', 'Ajustes'])
    await expect(menu.locator('nav svg')).toHaveCount(0)
    expect(await menu.evaluate((element) => getComputedStyle(element).backgroundColor)).toMatch(/rgba\(.+,\s*0\.[1-9]/)
    await expect(menu.locator('.main-menu-content')).toHaveCSS('transform', 'none')
    const close = menu.getByRole('button', { name: 'Fechar menu principal', exact: true })
    const lastChoiceBox = await choices.last().boundingBox()
    const closeBox = await close.boundingBox()
    expect(lastChoiceBox).not.toBeNull()
    expect(closeBox).not.toBeNull()
    expect(closeBox!.y).toBeGreaterThanOrEqual(lastChoiceBox!.y + lastChoiceBox!.height + 7.9)
    expect(closeBox!.width).toBeGreaterThanOrEqual(44)
    expect(closeBox!.height).toBeGreaterThanOrEqual(44)
    expect(await menu.locator('nav').evaluate((navigation, closeButton) => Boolean(navigation.compareDocumentPosition(closeButton as Node) & Node.DOCUMENT_POSITION_FOLLOWING), await close.elementHandle())).toBe(true)
    const content = await menu.locator('.main-menu-content').boundingBox()
    expect(content).not.toBeNull()
    if (content!.height <= size.height - 48) expect(Math.abs(content!.y + content!.height / 2 - size.height / 2)).toBeLessThan(8)
    else expect(content!.y).toBeGreaterThanOrEqual(12)
    expect(await page.evaluate(() => document.documentElement.style.overflow)).toBe('hidden')
    await close.click()
    await expect(menu).not.toBeVisible()
    await expect(trigger).toBeFocused()
    await expect(page.getByRole('heading', { name: 'Financeiro', exact: true })).toBeVisible()
  }
  await trigger.click()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog', { name: 'Menu principal' })).not.toBeVisible()
  await expect(trigger).toBeFocused()
  await trigger.click()
  await page.keyboard.press('Tab')
  await page.keyboard.press('Tab')
  await page.keyboard.press('Tab')
  const inside = await page.evaluate(() => document.querySelector('dialog[open]')?.contains(document.activeElement))
  expect(inside).toBe(true)
  await page.getByRole('dialog').getByRole('button', { name: 'Registros', exact: true }).click()
  await expect(page.getByRole('dialog', { name: 'Menu principal' })).not.toBeVisible()
  await expect(page.getByRole('heading', { name: 'Registros', exact: true })).toBeVisible()
  await expect(page.locator('#main-content')).toBeFocused()
  await expect(page.locator('.bottom-nav button')).toHaveCount(1)
  expect(await page.evaluate(() => document.documentElement.style.overflow)).not.toBe('hidden')
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await trigger.click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.screenshot({ path: test.info().outputPath(`menu-${theme}.png`) })
})
