import { useState } from 'react'
import { defaultSettings, localDateKey, MAX_BACKUP_BYTES, validateBackup, withScheduleStart } from '../../../core/domain'
import type { AppSettings, RoutineItem, StoragePersistence } from '../../../core/types'
import { PageTitle } from '../../../components/FormPrimitives'
import { repository } from '../../../infrastructure/repository'
import { routineItems } from '../../routine/data'
import { areaLabels } from '../../routine/view-labels'
import { effectiveTheme, type AppearanceFeedback, type EffectiveTheme } from '../theme'
import { ReminderSettings } from './ReminderSettings'

const readableError = (error: unknown, fallback: string) => error instanceof Error ? error.message : fallback

export function SettingsView({ settings, persistence, appearanceSaving, appearanceFeedback, onAppearance, onSettings, onMessage, onImported, onCleared }: { settings: AppSettings; persistence: StoragePersistence; appearanceSaving: boolean; appearanceFeedback: AppearanceFeedback; onAppearance: (theme: EffectiveTheme) => Promise<boolean>; onSettings: (settings: AppSettings) => Promise<void>; onMessage: (message: string) => void; onImported: () => void; onCleared: () => void }) {
  const [draft, setDraft] = useState(settings)
  const selectedTheme = effectiveTheme(settings.theme)
  async function updateAppearance(nextTheme: EffectiveTheme) {
    const previousTheme = selectedTheme
    setDraft((current) => ({ ...current, theme: nextTheme, appearanceVersion: 2 }))
    if (!await onAppearance(nextTheme)) setDraft((current) => ({ ...current, theme: previousTheme, appearanceVersion: 2 }))
  }
  function updateTime(item: RoutineItem, startTime: string) { setDraft((current) => withScheduleStart(current, item.id, startTime)) }
  function toggleActive(id: string) { setDraft((current) => ({ ...current, disabledActivities: current.disabledActivities.includes(id) ? current.disabledActivities.filter((item) => item !== id) : [...current.disabledActivities, id] })) }
  async function exportData() { try { const data = await repository.exportAll(); const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' }); const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = `ritmo-backup-${localDateKey()}.json`; document.body.appendChild(anchor); anchor.click(); anchor.remove(); window.setTimeout(() => URL.revokeObjectURL(url), 1000); onMessage('Backup JSON exportado.') } catch (error) { onMessage(readableError(error, 'Não foi possível exportar o backup.')) } }
  async function importData(file: File) { try { if (file.size > MAX_BACKUP_BYTES) return window.alert('O backup excede o limite de 10 MB. Nenhum dado foi alterado.'); const parsed: unknown = JSON.parse(await file.text()); if (!validateBackup(parsed)) return window.alert('Backup inválido ou de versão incompatível. Nenhum dado foi alterado.'); if (!window.confirm('Importar este backup substituirá todos os dados atuais. Deseja continuar?')) return; await repository.importAll(parsed); onImported() } catch { onMessage('Não foi possível ler ou importar o arquivo. Nenhum dado foi alterado.') } }
  async function clearData() { if (!window.confirm('Esta ação apagará permanentemente todos os registros deste aparelho e não pode ser desfeita. Continuar?')) return; try { await repository.clearAll(); onCleared() } catch (error) { onMessage(readableError(error, 'Não foi possível apagar os dados.')) } }
  const storageText = persistence === 'granted' ? 'Proteção persistente concedida' : persistence === 'checking' ? 'Verificando…' : persistence === 'unsupported' ? 'O navegador não informa proteção persistente' : 'Sujeito a limpeza pelo navegador — faça backups periódicos'
  return <><PageTitle eyebrow="Preferências e dados" title="Ajustes" subtitle="Sua rotina pode mudar junto com você." />
    <section className="settings-section"><h2>Aparência</h2><p className="section-description">Escolha como o Ritmo aparece neste aparelho. A mudança é salva imediatamente.</p><div className="appearance-options" role="group" aria-label="Aparência">{([['light', 'Claro'], ['dark', 'Escuro']] as const).map(([value, label]) => <button key={value} type="button" aria-pressed={selectedTheme === value} className={selectedTheme === value ? 'selected' : ''} disabled={appearanceSaving} onClick={() => updateAppearance(value)}>{label}</button>)}</div><p className={`appearance-status ${appearanceFeedback.kind}`} role={appearanceFeedback.kind === 'error' ? 'alert' : 'status'} aria-live={appearanceFeedback.kind === 'error' ? 'assertive' : 'polite'} aria-atomic="true" aria-label="Status da aparência">{appearanceFeedback.message}</p></section>
    <section className="settings-section"><div className="section-heading"><div><h2>Atividades e horários</h2><p className="section-description">Mostre o que importa e ajuste o início de cada atividade.</p></div></div><details className="settings-disclosure"><summary>Personalizar rotina <span>{routineItems.length} atividades</span></summary><div className="settings-list">{routineItems.map((item) => { const enabled = !draft.disabledActivities.includes(item.id); return <div className="setting-row" key={item.id}><button className={`toggle ${enabled ? 'on' : ''}`} role="switch" aria-checked={enabled} aria-label={`${enabled ? 'Desativar' : 'Ativar'} ${item.title}`} onClick={() => toggleActive(item.id)}><span /></button><div><strong>{item.title}</strong><small>{areaLabels[item.area]}</small></div><input aria-label={`Horário inicial de ${item.title}`} type="time" value={draft.scheduleOverrides[item.id]?.startTime ?? item.startTime ?? ''} onChange={(e) => updateTime(item, e.target.value)} /></div> })}</div></details><div className="settings-actions"><button className="primary-button" disabled={appearanceSaving} onClick={() => onSettings({ ...draft, theme: selectedTheme, appearanceVersion: 2 })}>Salvar ajustes</button><button className="text-button" onClick={() => { if (window.confirm('Restaurar atividades, horários, ritmo e semana do treino para os padrões? Salve para confirmar a mudança.')) setDraft({ ...defaultSettings(), theme: selectedTheme }) }}>Restaurar padrões</button></div></section>
    <ReminderSettings />
    <section className="settings-section"><h2>Dados neste aparelho</h2><div className="storage-status"><span className={persistence === 'granted' ? 'status-good' : 'status-warn'} aria-hidden="true" /><div><strong>Armazenamento local</strong><p>{storageText}</p></div></div><div className="action-grid"><button className="secondary-button" onClick={exportData}>Exportar backup JSON</button><label className="secondary-button file-button">Importar backup JSON<input type="file" accept="application/json,.json" onChange={(e) => e.target.files?.[0] && importData(e.target.files[0])} /></label></div><p className="fine-print">O app funciona sem conta e sem servidor. Guarde uma cópia do backup fora do celular periodicamente.</p></section>
    <section className="danger-section"><h2>Apagar todos os dados</h2><p>Remove registros, progresso e ajustes somente deste aparelho.</p><button className="danger-button" onClick={clearData}>Apagar registros</button></section></>
}
